#!/usr/bin/env bash

f()
{
	if [ ! -f $1 ]
	then
		echo "file not found $1" >&2
		exit 1
	fi

	echo "delete submodule: $1"
	git rm --cached $1    
	git config -f .git/config --remove-section submodule.$1     
	git config -f .gitmodules --remove-section submodule.$1
}

if [ $# = 1 ]
then
	GIT_ROOT=`git rev-parse --show-toplevel`
	(cd "$GIT_ROOT" && f $@)
else
	echo "usage: git submodule-delete <path to submodule>" >&2
	exit 1
fi